app:
  image: $IMAGE_NAME
  ports:
    - 8443:8443
  volumes:
    - ../:/app
  env_file: ../.env.development
  command: npm run dev
  links:
    - postgres
    - redis
    - swagger

postgres:
  image: $IMAGE_NAME-pgdb1
  ports:
    - 5432:5432

redis:
  image: $IMAGE_NAME-redisdb1
  ports:
    - 6379:6379

swagger:
  image: $IMAGE_NAME-swagger1
  environment:
    - API_URL=http://localhost:8080/api-docs.json
  ports:
    - 8080:8080