test-app:
  image: $IMAGE_NAME
  volumes:
    - ../bin:/app/bin
    - ../database:/app/database
    - ../scripts:/app/scripts
    - ../node_modules:/app/node_modules
    - ../public:/app/public
    - ../src:/app/src
    - ../sslcert:/app/sslcert
    - ../test:/app/test
    - ../.env.development:/app/.env.development
    - ../package.json:/app/package.json
  env_file: ../.env.test
  command: bash -c "chmod +x /app/scripts/wait-for-it.sh && npm test"
  links:
    - test-api
    - test-postgres

test-api:
  image: $IMAGE_NAME
  ports:
    - 8443:8443
  volumes:
    - ../:/app
  env_file: ../.env.test
  command: npm run dev
  links:
    - test-postgres
    - test-redis

test-postgres:
  image: $IMAGE_NAME-pgdb1
  ports:
    - 5432:5432

test-redis:
  image: $IMAGE_NAME-redisdb1
  ports:
    - 6379:6379