test-app:
  image: $IMAGE_NAME
  volumes:
    - ../:/app
  env_file: ../.env.test
  command: bash -c "chmod +x /app/scripts/wait-for-it.sh && npm test"
  links:
    - test-api
    - test-postgres

test-api:
  image: $IMAGE_NAME
  ports:
    - 8443:8443
  volumes:
    - ../:/app
  env_file: ../.env.test
  command: npm start
  links:
    - test-postgres
    - test-redis

test-postgres:
  image: $IMAGE_NAME-pgdb1
  ports:
    - 5432:5432

test-redis:
  image: $IMAGE_NAME-redisdb1
  ports:
    - 6379:6379